# Generated by Django 4.2 on 2024-11-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('categoria', models.BooleanField(default=False)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_final', models.CharField(blank=True, help_text='Nombre del producto final asociado a esta receta', max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad del insumo requerida para esta receta', max_digits=10)),
                ('insumo', models.ForeignKey(help_text='Insumo utilizado en la receta', on_delete=django.db.models.deletion.CASCADE, to='productos.productobase')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('presentacion', models.CharField(choices=[('Botella', 'Botella'), ('Vaso', 'Vaso'), ('Jarra', 'Jarra'), ('Cóctel', 'Cóctel'), ('Lata', 'Lata'), ('Sin Alcohol', 'Bebida sin alcohol')], max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('receta', models.ManyToManyField(blank=True, related_name='presentaciones', to='productos.receta')),
            ],
            options={
                'verbose_name': 'Presentación de Producto',
                'verbose_name_plural': 'Presentaciones de Productos',
            },
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.UniqueConstraint(fields=('producto_final', 'insumo'), name='unique_receta_insumo'),
        ),
    ]
