# Generated by Django 4.2 on 2024-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presentacion', models.CharField(max_length=100)),
                ('tipo_presentacion', models.CharField(choices=[('Botella', 'Botella Entera'), ('Vaso', 'Vaso'), ('Jarra', 'Jarra'), ('Coctel', 'Cóctel Preparado')], max_length=20)),
                ('consumo_por_presentacion_medidas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_ingrediente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('medidas', models.IntegerField()),
                ('stock_botellas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_medidas', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
