# Generated by Django 4.2 on 2025-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobase',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productobase',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
