# Generated by Django 4.2 on 2024-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_alter_inventario_producto'),
        ('compras', '0003_alter_compra_producto'),
        ('ventas', '0003_alter_comanda_producto_alter_venta_producto'),
        ('productos', '0002_presentacionproducto_productobase_receta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='receta',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacionproducto'),
        ),
        migrations.AddField(
            model_name='receta',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='productos.presentacionproducto'),
        ),
        migrations.AddField(
            model_name='presentacionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='productos.productobase'),
        ),
    ]
