# Generated by Django 4.2 on 2025-03-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productobase_precio_compra_productobase_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProductoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.IntegerField(default=1, help_text='Cantidad de esta presentación usada en el producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='presentacionproducto',
            options={},
        ),
        migrations.RemoveField(
            model_name='presentacionproducto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='presentacionproducto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='presentacionproducto',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='presentacionproducto',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='presentacionproducto',
            name='cantidad_medidas',
            field=models.IntegerField(default=1, help_text='Número de medidas que contiene'),
        ),
        migrations.AddField(
            model_name='presentacionproducto',
            name='producto_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='productos.productobase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productobase',
            name='contenido_neto',
            field=models.FloatField(default=1, help_text='Cantidad en la unidad de medida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productobase',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productobase',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productobase',
            name='unidad_medida',
            field=models.CharField(choices=[('botella', 'Botella'), ('litro', 'Litro'), ('onza', 'Onza'), ('unidad', 'Unidad')], default='unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='productobase',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.AddField(
            model_name='productomenu',
            name='presentaciones',
            field=models.ManyToManyField(through='productos.DetalleProductoMenu', to='productos.presentacionproducto'),
        ),
        migrations.AddField(
            model_name='detalleproductomenu',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacionproducto'),
        ),
        migrations.AddField(
            model_name='detalleproductomenu',
            name='producto_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productomenu'),
        ),
    ]
