# Generated by Django 4.2 on 2024-11-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_delete_producto_receta_ingrediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacionproducto',
            name='tipo_presentacion',
            field=models.CharField(choices=[('Botella', 'Botella Entera'), ('Vaso', 'Vaso'), ('Jarra', 'Jarra'), ('Coctel', 'Cóctel Preparado'), ('Cerveza', 'Lata/Botellin')], max_length=20),
        ),
    ]
