# Generated by Django 6.0.5 on 2026-05-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_detalleproductomenu_productomenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomenu',
            name='presentaciones',
        ),
        migrations.RemoveField(
            model_name='presentacionproducto',
            name='producto_base',
        ),
        migrations.AlterModelOptions(
            name='productobase',
            options={'ordering': ['nombre'], 'verbose_name': 'Insumo Base', 'verbose_name_plural': 'Insumos Base'},
        ),
        migrations.AlterModelOptions(
            name='productomenu',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Producto del Menu', 'verbose_name_plural': 'Productos del Menu'},
        ),
        migrations.RemoveField(
            model_name='productobase',
            name='contenido_neto',
        ),
        migrations.AddField(
            model_name='productobase',
            name='contenido_neto_ml',
            field=models.IntegerField(blank=True, help_text='Contenido neto en ml (ej: 750, 1000). Solo para botellas.', null=True),
        ),
        migrations.AddField(
            model_name='productobase',
            name='medidas_por_unidad',
            field=models.IntegerField(default=1, help_text='Cantidad de medidas por botella/unidad (ej: 16 para 750ml).'),
        ),
        migrations.AddField(
            model_name='productobase',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de costo unitario (por botella o unidad).', max_digits=10),
        ),
        migrations.AddField(
            model_name='productomenu',
            name='insumo_base',
            field=models.ForeignKey(blank=True, help_text='Insumo base asociado. No aplica para extras ni cocteles con receta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_menu', to='productos.productobase'),
        ),
        migrations.AddField(
            model_name='productomenu',
            name='medidas_por_venta',
            field=models.IntegerField(default=1, help_text='Medidas que se descuentan al vender. Solo para tipo vaso.'),
        ),
        migrations.AddField(
            model_name='productomenu',
            name='tipo',
            field=models.CharField(choices=[('botella', 'Botella entera'), ('vaso', 'Vaso / Medida suelta'), ('coctel_jarra', 'Coctel / Jarra'), ('extra', 'Extra (cerveza, refresco, etc.)')], default='extra', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productobase',
            name='unidad_medida',
            field=models.CharField(choices=[('botella', 'Botella'), ('unidad', 'Unidad')], default='botella', max_length=20),
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_medidas', models.DecimalField(decimal_places=1, help_text='Cantidad de medidas de este insumo en la receta.', max_digits=5)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_recetas', to='productos.productobase')),
                ('producto_menu', models.ForeignKey(limit_choices_to={'tipo': 'coctel_jarra'}, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='productos.productomenu')),
            ],
            options={
                'verbose_name': 'Item de Receta',
                'verbose_name_plural': 'Items de Receta',
            },
        ),
        migrations.DeleteModel(
            name='DetalleProductoMenu',
        ),
    ]
