# Generated by Django 6.0.5 on 2026-05-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_productomenu_presentaciones_and_more'),
        ('ventas', '0002_consolidacion_delete_cuenta_alter_comanda_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentacionProducto',
        ),
        migrations.AlterUniqueTogether(
            name='recetaitem',
            unique_together={('producto_menu', 'insumo')},
        ),
    ]
