# Generated by Django 4.2 on 2024-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_presentacionproducto_tipo_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacionproducto',
            name='nombre_presentacion',
            field=models.CharField(max_length=255),
        ),
    ]
