# Generated by Django 6.0.6 on 2026-07-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_delete_presentacionproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobase',
            name='categoria',
            field=models.CharField(blank=True, choices=[('whisky', 'Whisky'), ('tequila', 'Tequila'), ('ron', 'Ron'), ('vodka', 'Vodka'), ('gin', 'Gin'), ('fernet', 'Fernet'), ('singani', 'Singani'), ('varios', 'Varios'), ('cerveza', 'Cerveza'), ('soda', 'Sodas'), ('energizante', 'Energizante'), ('cigarrillo', 'Cigarrillos')], help_text='Categoría del insumo para filtrado en inventario.', max_length=20, null=True),
        ),
    ]
