# Generated by Django 6.0.6 on 2026-07-02 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_detallecompra_delete_pedido_alter_compra_options_and_more'),
        ('cuentas', '0001_initial'),
        ('productos', '0006_productobase_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('credito', 'Crédito')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Proveedor de esta compra.', max_length=100),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio real pagado por botella o unidad.', max_digits=10),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('planificacion', 'Planificación'), ('reposicion', 'Reposición'), ('extraordinario', 'Extraordinario')], default='planificacion', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('fecha_requerida', models.DateField(blank=True, help_text='Fecha para la que se necesita el pedido.', null=True)),
                ('monto_aprobado', models.DecimalField(decimal_places=2, default=0, help_text='Monto entregado al jefe de barra para ejecutar el pedido.', max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cierre_diario', models.ForeignKey(blank=True, help_text='Cierre diario al que pertenece (solo para pedidos extraordinarios).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_extraordinarios', to='cuentas.cierrediario')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(help_text='Nombre del proveedor (ej: DYM, INNOBE/ACTRA).', max_length=100)),
                ('cantidad_solicitada', models.IntegerField(default=1)),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=0, help_text='Precio estimado de referencia.', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('credito', 'Crédito')], default='transferencia', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='productos.productobase')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='pedido',
            field=models.ForeignKey(blank=True, help_text='Pedido al que pertenece esta compra (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='compras.pedido'),
        ),
    ]
