# Generated by Django 4.2 on 2024-11-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='compra',
        ),
    ]
