# Generated by Django 6.0.6 on 2026-07-27 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_metodo_pago_compra_proveedor_and_more'),
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('limpieza', 'Limpieza'), ('logistica', 'Logística'), ('alimentacion', 'Alimentación'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('credito', 'Crédito')], default='efectivo', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('cierre_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_operativos', to='cuentas.cierrediario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_operativos', to='compras.pedido')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_operativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-fecha'],
            },
        ),
    ]
