# Generated by Django 6.0.6 on 2026-07-29 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_gastooperativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastooperativo',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_operativos', to='compras.compra'),
        ),
    ]
