# Generated by Django 6.0.5 on 2026-05-20 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0006_alter_casohistorico_options_alter_parametro_options_and_more'),
        ('eventos', '0002_remove_evento_aforo_remove_evento_grupo_etario_and_more'),
        ('productos', '0004_remove_productomenu_presentaciones_and_more'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('resumen', models.JSONField(default=dict, help_text='JSON con el resumen de ventas por producto.')),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('consolidado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consolidacion',
                'verbose_name_plural': 'Consolidaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.AlterModelOptions(
            name='comanda',
            options={'ordering': ['-hora'], 'verbose_name': 'Comanda', 'verbose_name_plural': 'Comandas'},
        ),
        migrations.AlterModelOptions(
            name='sesiondetrabajo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Sesion de Trabajo', 'verbose_name_plural': 'Sesiones de Trabajo'},
        ),
        migrations.AddField(
            model_name='comanda',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesiondetrabajo',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='productos.productomenu'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sesiondetrabajo',
            name='usuario_encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_trabajo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidacion', to='ventas.sesiondetrabajo'),
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
