# Generated by Django 6.0.6 on 2026-08-05 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_cierrediario_evento'),
        ('eventos', '0002_remove_evento_aforo_remove_evento_grupo_etario_and_more'),
        ('productos', '0006_productobase_categoria'),
        ('ventas', '0002_consolidacion_delete_cuenta_alter_comanda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='sesion_de_trabajo',
        ),
        migrations.AlterModelOptions(
            name='comanda',
            options={'ordering': ['-creada_en'], 'verbose_name': 'Comanda', 'verbose_name_plural': 'Comandas'},
        ),
        migrations.AlterModelOptions(
            name='consolidacion',
            options={'ordering': ['-fecha_consolidacion'], 'verbose_name': 'Consolidación', 'verbose_name_plural': 'Consolidaciones'},
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='consolidacion',
            name='consolidado_por',
        ),
        migrations.RemoveField(
            model_name='consolidacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='consolidacion',
            name='resumen',
        ),
        migrations.AddField(
            model_name='comanda',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='anulada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que autorizó la anulación (debe ser bartender o admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='creada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('lista', 'Lista'), ('entregada', 'Entregada'), ('cobrada', 'Cobrada'), ('anulada', 'Anulada')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='comanda',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comanda',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia libre opcional (ej: Mesa 3, Cumpleañero, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='cierre_diario',
            field=models.ForeignKey(blank=True, help_text='Cierre diario al que pertenece esta consolidación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidaciones', to='cuentas.cierrediario'),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='total_anuladas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='total_comandas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidacion',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consolidacion',
            name='fecha_consolidacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta.', max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.comanda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_comanda', to='productos.productomenu')),
            ],
            options={
                'verbose_name': 'Item de comanda',
                'verbose_name_plural': 'Items de comanda',
            },
        ),
        migrations.CreateModel(
            name='SesionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_barra', models.BooleanField(default=False, help_text='True si esta sesión corresponde a la barra.')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_trabajo', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de trabajo',
                'verbose_name_plural': 'Sesiones de trabajo',
                'ordering': ['-fecha_apertura'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='comanda',
            name='sesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='ventas.sesiontrabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consolidacion',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consolidacion', to='ventas.sesiontrabajo'),
        ),
        migrations.DeleteModel(
            name='SesionDeTrabajo',
        ),
    ]
