# Generated by Django 6.0.6 on 2026-08-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0008_alter_casohistorico_sesion'),
        ('ventas', '0003_remove_comanda_sesion_de_trabajo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consolidacion',
        ),
    ]
