# Generated by Django 6.0.6 on 2026-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_delete_consolidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomanda',
            name='observacion',
            field=models.CharField(blank=True, help_text='Nota para barra (ej: sin hielo, con limón)', max_length=200),
        ),
    ]
