# Generated by Django 4.2 on 2024-11-15 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_presentacionproducto_tipo_presentacion'),
        ('ventas', '0005_delete_cuentas_sesiondetrabajo_usuario_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.presentacionproducto'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='sesion_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.sesiondetrabajo'),
        ),
    ]
