# Generated by Django 4.2 on 2024-11-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_presentacionproducto_tipo_presentacion'),
        ('ventas', '0006_alter_comanda_cantidad_alter_comanda_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='comanda',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='sesion_de_trabajo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='presentacion_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.presentacionproducto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
