# Generated by Django 4.2 on 2024-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_venta_comanda_remove_venta_sesion_de_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
