# Generated by Django 6.0.5 on 2026-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('jefe_barra', 'Jefe de Barra'), ('bartender', 'Bartender'), ('mesero', 'Mesero')], max_length=50, null=True),
        ),
    ]
