# Generated by Django 4.2 on 2024-11-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='cuentas',
            name='ventas',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='compras',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='registrostock',
            name='inventario',
        ),
        migrations.DeleteModel(
            name='Casos',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Comanda',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.DeleteModel(
            name='Cuentas',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='RegistroStock',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
