# Generated by Django 6.0.6 on 2026-06-23 04:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_remove_evento_aforo_remove_evento_grupo_etario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('caja_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Monto en caja chica al inicio del día (CAJA DIARIA)', max_digits=10)),
                ('caja_hay', models.DecimalField(blank=True, decimal_places=2, help_text='Arqueo real de caja al cierre (HAY)', max_digits=10, null=True)),
                ('ingresos_ventas_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Total de ventas ingresado manualmente', max_digits=10, null=True)),
                ('usar_ventas_manual', models.BooleanField(default=True)),
                ('monto_pedido_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacion_pedido', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Cierre diario',
                'verbose_name_plural': 'Cierres diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CierreBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(choices=[('equi_c1', 'Equi C1'), ('equi_c2', 'Equi C2'), ('equi_c3', 'Equi C3')], max_length=20)),
                ('lote', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_bancarios', to='cuentas.cierrediario')),
            ],
            options={
                'verbose_name': 'Cierre bancario',
                'verbose_name_plural': 'Cierres bancarios',
            },
        ),
        migrations.CreateModel(
            name='EgresoGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('pedido', 'Pedido'), ('cocas', 'Cocas/Insumos'), ('logistica', 'Logística'), ('otro', 'Otro')], max_length=20)),
                ('concepto_otro', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_grandes', to='cuentas.cierrediario')),
            ],
            options={
                'verbose_name': 'Egreso grande',
                'verbose_name_plural': 'Egresos grandes',
            },
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_diarios', to='cuentas.cierrediario')),
            ],
            options={
                'verbose_name': 'Gasto diario',
                'verbose_name_plural': 'Gastos diarios',
            },
        ),
        migrations.CreateModel(
            name='OtroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('ropa', 'Ropa'), ('merchandising', 'Merchandising'), ('equi_16', 'Equi 16%'), ('otro', 'Otro')], max_length=20)),
                ('concepto_otro', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_ingresos', to='cuentas.cierrediario')),
            ],
            options={
                'verbose_name': 'Otro ingreso',
                'verbose_name_plural': 'Otros ingresos',
            },
        ),
        migrations.CreateModel(
            name='ResumenSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cierres', models.ManyToManyField(related_name='resumenes', to='cuentas.cierrediario')),
            ],
            options={
                'verbose_name': 'Resumen semanal',
                'verbose_name_plural': 'Resúmenes semanales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SueldoNoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libre', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje de caja'), ('fijo', 'Monto fijo')], max_length=20)),
                ('caja_mesero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sueldo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sueldos', to='cuentas.cierrediario')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sueldos_noche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sueldo de noche',
                'verbose_name_plural': 'Sueldos de noche',
            },
        ),
        migrations.CreateModel(
            name='EntregaMesera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_barra', models.BooleanField(default=False, help_text='True si esta entrega corresponde a la barra')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='QR')),
                ('voucher_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('total_talonario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_meseras', to='cuentas.cierrediario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'unique_together': {('cierre', 'usuario', 'es_barra')},
            },
        ),
    ]
