# Generated by Django 6.0.6 on 2026-07-30 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_gastooperativo_compra'),
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastodiario',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='cierrediario',
            name='caja_hay',
        ),
        migrations.RemoveField(
            model_name='cierrediario',
            name='ingresos_ventas_manual',
        ),
        migrations.RemoveField(
            model_name='cierrediario',
            name='monto_pedido_semanal',
        ),
        migrations.RemoveField(
            model_name='cierrediario',
            name='observacion_pedido',
        ),
        migrations.RemoveField(
            model_name='cierrediario',
            name='usar_ventas_manual',
        ),
        migrations.AddField(
            model_name='egresogrande',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cierrediario',
            name='caja_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo inicial del fondo de caja chica al abrir la noche.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresogrande',
            name='concepto',
            field=models.CharField(choices=[('alquiler_equipo', 'Alquiler de equipo'), ('pago_artista', 'Pago a artista/DJ'), ('retiro_dueno', 'Retiro del dueño'), ('cuetes', 'Cuetes/Pirotecnia'), ('decoracion', 'Decoración'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='otroingreso',
            name='concepto',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('merchandising', 'Merchandising'), ('cover', 'Cover / Entradas'), ('equi_16', 'Equi 16%'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.CreateModel(
            name='EntregaPuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_barra', models.BooleanField(default=False, help_text='True si esta entrega corresponde a la barra.')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='QR')),
                ('voucher_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_talonario', models.DecimalField(blank=True, decimal_places=2, help_text='Total de ventas según talonario.', max_digits=10, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_punto_venta', to='cuentas.cierrediario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_punto_venta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de punto de venta',
                'verbose_name_plural': 'Entregas de punto de venta',
                'unique_together': {('cierre', 'usuario', 'es_barra')},
            },
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('alquiler', 'Alquiler'), ('prohigiene', 'Prohigiene'), ('internet', 'Internet'), ('otro', 'Otro')], max_length=20)),
                ('concepto_otro', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago', models.DateField()),
                ('periodo_mes', models.IntegerField(help_text='Mes al que corresponde (1-12)')),
                ('periodo_anio', models.IntegerField(help_text='Año al que corresponde')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='transferencia', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='gastos_fijos/%Y/%m/')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_fijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto fijo',
                'verbose_name_plural': 'Gastos fijos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('egreso', 'Egreso'), ('ingreso', 'Ingreso')], default='egreso', max_length=10)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_chica', to='cuentas.cierrediario')),
                ('gasto_operativo', models.ForeignKey(blank=True, help_text='Gasto operativo asociado si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_chica', to='compras.gastooperativo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_chica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de caja chica',
                'verbose_name_plural': 'Movimientos de caja chica',
                'ordering': ['cierre__fecha'],
            },
        ),
        migrations.DeleteModel(
            name='EntregaMesera',
        ),
        migrations.DeleteModel(
            name='GastoDiario',
        ),
    ]
