# Generated by Django 6.0.6 on 2026-08-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_gastodiario_cierre_and_more'),
        ('eventos', '0002_remove_evento_aforo_remove_evento_grupo_etario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrediario',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='eventos.evento'),
            preserve_default=False,
        ),
    ]
