# Generated by Django 6.0.6 on 2026-08-18 08:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_cierrediario_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_qr', to='cuentas.entregapuntoventa')),
            ],
            options={
                'verbose_name': 'Comprobante QR',
                'verbose_name_plural': 'Comprobantes QR',
                'ordering': ['creado_en'],
            },
        ),
    ]
