# Generated by Django 6.0.6 on 2026-08-19 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_comprobanteqr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregapuntoventa',
            name='ajustado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_talonario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregapuntoventa',
            name='fecha_ajuste_talonario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregapuntoventa',
            name='motivo_ajuste_talonario',
            field=models.CharField(blank=True, help_text='Motivo del ajuste manual (obligatorio si un admin corrige el total).', max_length=300),
        ),
        migrations.AddField(
            model_name='entregapuntoventa',
            name='origen_talonario',
            field=models.CharField(choices=[('sistema', 'Sistema (automático)'), ('manual', 'Ajuste manual')], default='sistema', help_text='Indica si el total viene del cálculo automático de ventas o fue corregido a mano por un administrador.', max_length=10),
        ),
        migrations.AlterField(
            model_name='entregapuntoventa',
            name='total_talonario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de ventas según talonario. Se sincroniza automáticamente desde SesionTrabajo salvo que haya sido ajustado manualmente.', max_digits=10, null=True),
        ),
    ]