# Generated by Django 4.2 on 2024-11-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo', models.CharField(blank=True, max_length=30, null=True)),
                ('total_asistentes', models.IntegerField(default=0)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grupo_etario', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Covers',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers/')),
                ('tipo', models.CharField(blank=True, choices=[('CONCIERTO', 'Concierto'), ('FIESTA', 'Fiesta'), ('CONFERENCIA', 'Conferencia'), ('OTRO', 'Otro'), ('TRIBUTO', 'Tributo')], max_length=50, null=True)),
                ('banda', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField()),
                ('aforo', models.IntegerField(blank=True, null=True)),
                ('grupo_etario', models.CharField(blank=True, choices=[('MAYORES', '18-25 años'), ('ADULTOS', '26-35 años'), ('CLASICOS', '36-45 años')], max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cover', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_cover', to='eventos.cover')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
