# Generated by Django 4.2 on 2024-11-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='aforo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='grupo_etario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
    ]
