# Generated by Django 6.0.6 on 2026-08-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_aforo_remove_evento_grupo_etario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cover',
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='porcentaje_bar',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje de recaudación cover que va al bar.', max_digits=5),
        ),
        migrations.AddField(
            model_name='evento',
            name='porcentaje_grupo',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Porcentaje de recaudación cover que va al grupo/artista.', max_digits=5),
        ),
        migrations.CreateModel(
            name='EntradaCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('preventa', 'Preventa'), ('promo', 'Promoción'), ('gratis', 'Chicas gratis'), ('dos_x_uno', '2x1'), ('vip', 'VIP'), ('invitado', 'Invitado')], max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_cover', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Entrada Cover',
                'verbose_name_plural': 'Entradas Cover',
                'unique_together': {('evento', 'tipo')},
            },
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
