# Generated by Django 4.2 on 2024-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_presentacionproducto_productobase_receta_and_more'),
        ('inventarios', '0002_remove_producto_categoria_alter_inventario_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productobase'),
        ),
    ]
