# Generated by Django 6.0.5 on 2026-05-20 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0006_alter_casohistorico_options_alter_parametro_options_and_more'),
        ('inventarios', '0002_alter_inventario_saldo_bodega'),
        ('productos', '0003_detalleproductomenu_productomenu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('botellas_contadas', models.IntegerField(default=0)),
                ('medidas_contadas', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='productos.productobase')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura Diaria',
                'verbose_name_plural': 'Aperturas Diarias',
                'unique_together': {('fecha', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Consolidacion de ventas'), ('ajuste', 'Ajuste manual'), ('apertura', 'Apertura diaria')], max_length=20)),
                ('botellas', models.IntegerField(default=0)),
                ('medidas', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, help_text='Referencia al documento origen (compra, sesion, etc.)', max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.productobase')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='RegistroStock',
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='saldo_bodega',
            new_name='botellas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='medidas_restantes',
        ),
        migrations.AddField(
            model_name='inventario',
            name='medidas_sueltas',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.productobase'),
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
