# Generated by Django 4.2 on 2024-11-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('eventos', '0001_initial'),
        ('compras', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField()),
                ('label1', models.CharField(max_length=15)),
                ('label2', models.CharField(max_length=15)),
                ('cuentas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='ventas.cuentas')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='eventos.evento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='compras.pedido')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='inventarios.registrostock')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
            },
        ),
    ]
