# Generated by Django 4.2 on 2024-11-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cuenta_sesiondetrabajo_remove_cuentas_ventas_and_more'),
        ('analizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='cuentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='ventas.cuenta'),
        ),
    ]
