# Generated by Django 4.2 on 2024-11-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('ventas', '0001_initial'),
        ('inventarios', '0001_initial'),
        ('analizador', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='cuentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='ventas.cuenta'),
        ),
        migrations.AddField(
            model_name='caso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='caso',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='compras.pedido'),
        ),
        migrations.AddField(
            model_name='caso',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='inventarios.registrostock'),
        ),
    ]
