# Generated by Django 4.2 on 2024-11-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        ('inventarios', '0002_alter_inventario_saldo_bodega'),
        ('eventos', '0001_initial'),
        ('compras', '0002_initial'),
        ('analizador', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('nombre_evento', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('eficacia', models.FloatField(default=0.0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_históricos', to='ventas.cuenta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_históricos', to='eventos.evento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_históricos', to='inventarios.registrostock')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_históricos', to='compras.pedido')),
            ],
            options={
                'verbose_name': 'Caso Histórico',
                'verbose_name_plural': 'Casos Históricos',
            },
        ),
        migrations.CreateModel(
            name='ParametrosEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aforo_esperado', models.IntegerField()),
                ('ventas_esperadas', models.IntegerField()),
                ('consumo_esperado', models.IntegerField()),
                ('tipo_evento', models.CharField(max_length=255)),
                ('show_presentado', models.CharField(max_length=255)),
                ('genero_musical', models.CharField(max_length=255)),
                ('promociones', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255)),
                ('cantidad_recomendada', models.IntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Caso',
        ),
    ]
