# Generated by Django 4.2 on 2024-11-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0003_casohistorico_parametrosentrada_recomendacioncompra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('desplegable', 'Desplegable'), ('difuso', 'Difuso')], max_length=50)),
                ('opciones', models.JSONField(default=list)),
            ],
        ),
    ]
