# Generated by Django 6.0.5 on 2026-05-20 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0005_remove_casohistorico_artista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casohistorico',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Caso Historico', 'verbose_name_plural': 'Casos Historicos'},
        ),
        migrations.AlterModelOptions(
            name='parametro',
            options={'verbose_name': 'Parametro', 'verbose_name_plural': 'Parametros'},
        ),
        migrations.AlterModelOptions(
            name='parametrosentrada',
            options={'verbose_name': 'Parametros de Entrada', 'verbose_name_plural': 'Parametros de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='recomendacioncompra',
            options={'verbose_name': 'Recomendacion de Compra', 'verbose_name_plural': 'Recomendaciones de Compra'},
        ),
        migrations.RemoveField(
            model_name='casohistorico',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='casohistorico',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='casohistorico',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='casohistorico',
            name='show_presentado',
        ),
        migrations.RemoveField(
            model_name='parametrosentrada',
            name='show_presentado',
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='aforo_esperado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='consumo_per_capita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='recomendacion_compra',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='resumen_inventario',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='resumen_ventas',
            field=models.JSONField(default=dict),
        ),
    ]
