# Generated by Django 6.0.5 on 2026-05-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0006_alter_casohistorico_options_alter_parametro_options_and_more'),
        ('eventos', '0002_remove_evento_aforo_remove_evento_grupo_etario_and_more'),
        ('ventas', '0002_consolidacion_delete_cuenta_alter_comanda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casohistorico',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_historicos', to='ventas.consolidacion'),
        ),
        migrations.AddField(
            model_name='casohistorico',
            name='ventas_esperadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='casohistorico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_historicos', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='casohistorico',
            name='genero_musical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casohistorico',
            name='tipo_evento',
            field=models.CharField(default='Concierto', max_length=255),
        ),
        migrations.AlterField(
            model_name='parametrosentrada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='parametrosentrada',
            name='genero_musical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosentrada',
            name='promociones',
            field=models.CharField(default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='recomendacioncompra',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='eventos.evento'),
        ),
    ]
