# Generated by Django 6.0.6 on 2026-08-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0007_casohistorico_sesion_casohistorico_ventas_esperadas_and_more'),
        ('ventas', '0003_remove_comanda_sesion_de_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casohistorico',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_historicos', to='ventas.sesiontrabajo'),
        ),
    ]
